// <auto-generated />
using System;
using FourPawsCleanArchitecture.Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FourPawsCleanArchitecture.Infraestructure.Migrations
{
    [DbContext(typeof(SqlServeDbContext))]
    [Migration("20230518002354_Update table categoria")]
    partial class Updatetablecategoria
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FourPawsCleanArchitecture.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Código da categoria");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Nome da categoria");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("'A'")
                        .HasComment("Status da categoria: A;Ativo;I;Inativo;D;Deletado");

                    b.HasKey("Codigo");

                    b.ToTable("Categorias");

                    b.HasComment("Tabela das categoria dos produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
